<?php

namespace AppBundle\Repository;

/**
 * AdapterSettingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdapterSettingRepository extends \Doctrine\ORM\EntityRepository
{
	/**
	 * This function receives the id of one adapter and returns all its loaded settings in the database
	 * as an array, which might have a nested array depending on data repeatability
	 *
	 * @param Adapter $adapter
	 *
	 * @return array
	 */
	public function getAdapterSettings($adapter)
	{
		/**
		 * @var AdapterSetting[] $settings
		 */
		$result   = [];
		$settings = $this->findBy(['adapter' => $adapter]);

		foreach ($settings as $setting) {
			$key          = $setting->getName();
			$value        = $setting->getValue();
			$result[$key] = $value;
		}

		return $result;
	}

	/**
	 * Update the settings of the adapter
	 *
	 * @param Adapter $adapter
	 * @param array $settings
	 *
	 * @return boolean
	 */
	public function updateAdapterSettings($adapter, $settings)
	{
		try {
			foreach ($settings as $name => $value) {

				// Find the setting
				$setting = $this->findOneBy([
					'adapter' => $adapter,
					'name' => $name
				]);

				// Update the setting
				$setting->setValue($value);
			}

			// Save changes
			$this->getEntityManager()->flush();

			// settings were updated successfully
			return true;
		} catch (\Exception $e) {
			return false;
		}
	}
}
