<?php

namespace AppBundle\Repository;

/**
 * AdapterSettingOptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdapterSettingOptionRepository extends \Doctrine\ORM\EntityRepository
{
}
