<?php

namespace AppBundle\Repository;

/**
 * AdapterTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdapterTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
