<?php

namespace AppBundle\Repository;

/**
 * AdapterStatsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdapterStatisticRepository extends \Doctrine\ORM\EntityRepository
{
}
