<?php

namespace AppBundle\Repository;

/**
 * ApiRateLimitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApiRateLimitRepository extends \Doctrine\ORM\EntityRepository
{
}
