<?php

namespace ImportsBundle\Repository;

use Doctrine\ORM\EntityRepository;
use ImportsBundle\Entity\Workflow;
use ImportsBundle\Entity\FileImportModuleInstance;
use ImportsBundle\Entity\ModuleInstance;
use ImportsBundle\Enumeration\EnumExecutionStatus;

/**
 * AdapterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FileImportModuleInstanceRepository extends EntityRepository
{
    /**
     * @param Workflow $fileImport
     * @param ModuleInstance $moduleInstance
     * @return FileImportModuleInstance
     */
	public function saveFileImportModuleInstance(Workflow $fileImport, ModuleInstance $moduleInstance)
	{
		$fileImportModuleInstance = new FileImportModuleInstance();
        $fileImportModuleInstance->setFileImport($fileImport);
        $fileImportModuleInstance->setModuleInstance($moduleInstance);
        $fileImportModuleInstance->setExecutionStatus(EnumExecutionStatus::ADAPTATION_PENDING);
        $fileImportModuleInstance->setStartedAt(null);

		// Persist File Import Object
		$this->getEntityManager()->persist($fileImportModuleInstance);
		$this->getEntityManager()->flush();

		// Return fileImport object
		return $fileImportModuleInstance;
	}

}
