<?php

namespace AppBundle\Repository;

/**
 * ModuleSettingTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModuleSettingTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
