<?php

namespace AppBundle\Repository;

/**
 * ModuleSettingOptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModuleSettingOptionRepository extends \Doctrine\ORM\EntityRepository
{
}
