<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Module;

/**
 * ModuleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModuleRepository extends \Doctrine\ORM\EntityRepository
{
	public function listAllModules()
	{
		/**
		 * @var Module $module
		 */
		$modules = [];
		$allModules = $this->findBy(array(), array('name' => 'ASC'));
		foreach ($allModules as $module) {
			$modules[$module->getModuleId()] = $module->getName();
		}
		return $modules;
	}
}
