<?php

namespace AppBundle\Repository;

/**
 * WorkflowContactBatchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkflowContactBatchRepository extends \Doctrine\ORM\EntityRepository
{
}
