<?php

namespace AppBundle\Repository;

/**
 * WorkflowContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkflowContactRepository extends \Doctrine\ORM\EntityRepository
{
}
