<?php

namespace AppBundle\Repository;

/**
 * WorkflowRecordingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkflowRecordingRepository extends \Doctrine\ORM\EntityRepository
{
}
