<?php

namespace CequensBundle\Repository;

/**
 * ApplicationPropertyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationPropertyRepository extends \Doctrine\ORM\EntityRepository
{
}
