<?php

namespace CequensBundle\Repository;

/**
 * AudioFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AudioFileRepository extends \Doctrine\ORM\EntityRepository
{
}
