<?php

namespace CequensBundle\Repository;

/**
 * BotAgentQuickReplyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BotAgentQuickReplyRepository extends \Doctrine\ORM\EntityRepository
{
}
