<?php

namespace CequensBundle\Repository;

/**
 * BotUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BotUserRepository extends \Doctrine\ORM\EntityRepository
{
}
