<?php

namespace CequensBundle\Repository;

use CequensBundle\Entity\ConversationMessage;

/**
 * ConversationMessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConversationMessageRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return ConversationMessage[]
     */
    public function findByUserIdOrderedByDate($userId)
    {
        $entityManager = $this->getEntityManager();

        $query = $entityManager->createQuery(
            'SELECT p FROM CequensBundle\Entity\ConversationMessage p where
             (p.senderId = :userId or p.recId = :userId)  ORDER BY p.sendDate ASC'
        )->setParameter('userId',$userId);

        // returns an array of Product objects
        return $query->execute();
    }

    /**
     * @return ConversationMessage[]
     */
    public function findUserMessagesOrderedByDate()
    {
        $entityManager = $this->getEntityManager();

        $query = $entityManager->createQuery('SELECT p.senderId,p.senderType FROM CequensBundle\Entity\ConversationMessage p where (p.senderType = :senderTy or p.senderType = :senderTyy) group by p.senderId, p.senderType'
        )->setParameter('senderTy','FB-User')
        ->setParameter('senderTyy','WhatsApp-User');

        // returns an array of Product objects
        return $query->execute();
    }
}
