<?php

namespace CequensBundle\Repository;

/**
 * PropertyOptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PropertyOptionRepository extends \Doctrine\ORM\EntityRepository
{
}
