<?php

namespace CequensBundle\Repository;

/**
 * PropertyGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PropertyGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
