<?php

namespace CequensBundle\Repository;

/**
 * TriggeredKeysRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TriggeredKeysRepository extends \Doctrine\ORM\EntityRepository
{
}
